### ISSUE TITLE
Configurations

### ISSUE THREAD

**Issue by markov00** [markov00/dotfiles#5]
- [ ] chrome url shortcuts
- [ ] remove mission control key bindings (avoid binding the ctrl key)
- [ ] add iterm2 `quake-terminal-like` preferences
- [ ] add git config via wizard
- [ ] add atom configuration + plugins
- [ ] remove swipe between pages with touchpad
